# Generated by Django 3.1.1 on 2020-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0002_auto_20201005_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='order',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
