# Generated by Django 3.1.1 on 2020-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0004_auto_20201007_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='note',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
